# Generated by Django 5.0.12 on 2025-03-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MexcentrixAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummy_field', models.BooleanField(default=True)),
            ],
            options={
                'permissions': [('access_mexcentrix', 'Puede acceder a la app Mexcentrix')],
            },
        ),
    ]
