# Generated by Django 5.0.9 on 2024-10-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration class for the 'Empleado' model.
    
    This is the initial migration, creating the 'Empleado' model
    with its associated fields in the database.
    """
    
    initial = True  # Indicates this is the first migration for the app

    dependencies = [
        # List of dependencies for this migration
        # This migration has no dependencies on other migrations
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.CharField(max_length=255)),
                ('auth_datetime', models.DateTimeField()),
                ('auth_date', models.DateField()),
                ('auth_time', models.TimeField()),
                ('address', models.CharField(max_length=255)),
                ('device_name', models.CharField(max_length=255)),
                ('device_serial', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('card_no', models.CharField(max_length=255)),
            ],
        ),
    ]
