# Generated by Django 5.0.12 on 2025-03-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'permissions': [('is_finance', 'Puede acceder al área de Finanzas'), ('is_developer', 'Puede acceder al área de Desarrollo'), ('is_rh', 'Puede acceder al área de Recursos Humanos')],
            },
        ),
    ]
