# Generated by Django 5.0.12 on 2025-03-18 19:13

from django.db import migrations


def populate_companies(apps, schema_editor):
    Company = apps.get_model('mi_aplicacion', 'Company')
    domains_companies = {
        "mxcxit": {
            "mxcxit_htcerp": "HTC",
            "mxcxit_mexxonerp": "MEXXON",
            "mxcxit_rsserp": "RSS",
            "mxcxit_ripmerp": "RIPM",
            "mxcxit_spqerp": "SPQ"
        },
        "mexcx": {
            "mexcx_asiaop": "ASIA OP",
            "mexcx_daimayerp": "DAIMAY",
            "mexcx_hmserp": "HMS"
        },
        "mxcenit": {
            "mxcenit_sicerp": "SIC",
            "mxcenit_tbgerp": "TBG QRO",
            "mxcenit_tbgerp2": "TBG MEX"
        }
    }
    
    for domain, companies in domains_companies.items():
        for code, name in companies.items():
            Company.objects.get_or_create(code=code, name=name, domain=domain)
            
class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0003_company_usercompany'),
    ]

    operations = [
        migrations.RunPython(populate_companies),
    ]
