# Generated by Django 5.0.12 on 2025-03-26 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0004_populate_companies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionstest',
            options={'permissions': [('is_finance', 'Puede acceder al área de Finanzas'), ('is_developer', 'Puede acceder al área de Desarrollo'), ('is_rh', 'Puede acceder al área de Recursos Humanos'), ('is_trade', 'Puede acceder al área de Comercio')]},
        ),
    ]
